# Generated by Django 5.0.8 on 2025-05-20 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_post_created_at_alter_reel_created_at_hashtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='content/img'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reel',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='content/sound'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='content/img'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='content/video'),
        ),
    ]
