# Generated by Django 5.0.8 on 2025-05-22 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_post_likes_alter_post_thumbnail_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="post",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="reel",
            name="updated_at",
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="content/img"),
                ),
                ("description", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="content_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="content_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="content.content",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reel",
            name="content_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="content.content",
            ),
            preserve_default=False,
        ),
    ]
