# Generated by Django 5.0.8 on 2025-05-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_post_created_at_remove_post_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='media/content')),
            ],
            bases=('content.content',),
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='reels',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='contents',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='content.content'),
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
    ]
