# Generated by Django 5.0.8 on 2024-10-12 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="reciver",
            new_name="receiver",
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("requester", "receiver")},
        ),
    ]
