# Generated by Django 5.0.8 on 2025-07-26 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0003_alter_connection_is_accept"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["requester", "receiver"], name="connect_con_request_ce3daa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["receiver", "requester"], name="connect_con_receive_ee3d8a_idx"
            ),
        ),
    ]
